### ISSUE TITLE
ModuleNotFoundError: No module named 'distribute_setup'

### ISSUE THREAD

**Issue by akileshrajan** [DasIch/opts#6]
Trying to install opts for a project.! But the distribute_setup file doesn't seem to be available in the package on PyPI.
Attaching the error log below for further information.

```
Collecting opts
  Using cached opts-0.1.1.tar.gz (6.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/akilesh/.virtualenvs/center/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ypysq77q/opts/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ypysq77q/opts/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bk3rnfqe
         cwd: /tmp/pip-install-ypysq77q/opts/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ypysq77q/opts/setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by Haoju-Leng** [comment]
I'm having the same issue! do you know how to solve it?
